Make smaller floppies because they are overfilling.
nitros9project/nitros9 pull request #37
Opened 2023-12-31 05:25 UTC by strickyak

1.  The defs/*.d files for each type of build will have redundant spaces removed.  This cuts their file length almost in half.

2.  Create a third disk in the 40d_*.dsk set for coco3 and coco3_6309 modules.

3.  Minor change to comment in level2/modules/rbf.asm to remove an RCS ID from the source file.

This is enough changes for coco-shelf to build.
(There may be other broken platforms that coco-shelf does not make.)

2023-12-31 18:21 UTC, strickyak commented
These manual steps also succeed, with this PR:

$  PATH=/home/strick/coco-shelf/bin/:$PATH  NITROS9DIR=`pwd`  make
$  PATH=/home/strick/coco-shelf/bin/:$PATH  NITROS9DIR=`pwd`  make dsk

2024-01-03 18:37 UTC, boisy requested changes

2024-01-03 18:37 UTC, DrPitre commented on rules.mak
> +DROP_EXTRA_SPACES = sed --in-place=.tmp -e 's/  */ /g'
@strickyak can we change --in-place= to -I<space>? macOS' sed doesn't recognize that option.

2024-01-03 19:34 UTC, strickyak commented on rules.mak
> +DROP_EXTRA_SPACES = sed --in-place=.tmp -e 's/  */ /g'
Changed to use portable Bourne Shell function and simple portable sed.

2024-01-03 21:07 UTC, boisy approved these changes

2024-01-03 22:55 UTC, merged